import https from 'https';
import { URL } from 'url';
import { CheckResult, RiskIndicator } from './check.types.ts';
import type { CheckStatus } from './check.types.ts';

export interface SslCheckResult {
  check: CheckResult;
  risks: RiskIndicator[];
}

export class SslCheckService {
  static async check(url: string): Promise<SslCheckResult> {
    const risks: RiskIndicator[] = [];
    let status: CheckStatus = 'PASSED';
    let score = 20;
    let result = 'HTTPS available';
    let details = '';
    const evidence: Record<string, any> = { url };

    // Ensure URL uses HTTPS
    let httpsUrl = url;
    if (!url.startsWith('https://')) {
      if (url.startsWith('http://')) {
        httpsUrl = url.replace('http://', 'https://');
      } else {
        httpsUrl = `https://${url}`;
      }
    }

    evidence.requestedUrl = url;
    evidence.httpsUrl = httpsUrl;

    try {
      const certInfo = await this.fetchCertificate(httpsUrl);
      evidence.certificate = {
        subject: certInfo.subject,
        issuer: certInfo.issuer,
        validFrom: certInfo.validFrom,
        validTo: certInfo.validTo,
        valid: certInfo.valid,
        autoGenerated: certInfo.autoGenerated,
      };

      const now = new Date();
      const validFrom = new Date(certInfo.validFrom);
      const validTo = new Date(certInfo.validTo);

      if (certInfo.valid) {
        const daysRemaining = Math.floor((validTo.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));
        evidence.daysRemaining = daysRemaining;

        if (daysRemaining < 30) {
          status = 'WARNING';
          score = 10;
          result = 'Certificate expiring soon';
          details = `Certificate expires in ${daysRemaining} days.`;
          risks.push({
            type: 'CERTIFICATE_EXPIRING',
            severity: 'LOW',
            title: 'Certificate Expiring Soon',
            description: `The TLS certificate for this domain expires in ${daysRemaining} days.`,
            evidence: { validTo: certInfo.validTo, daysRemaining },
          });
        } else {
          result = 'Valid HTTPS certificate';
          details = `Certificate is valid. Issued by ${certInfo.issuer}. Expires ${validTo.toISOString().split('T')[0]}.`;
        }
      } else {
        status = 'FAILED';
        score = 0;
        result = 'Invalid certificate';
        details = certInfo.error || 'Certificate validation failed.';
        risks.push({
          type: 'INVALID_CERTIFICATE',
          severity: 'MEDIUM',
          title: 'Invalid TLS Certificate',
          description: details,
          evidence: { issuer: certInfo.issuer, validFrom: certInfo.validFrom, validTo: certInfo.validTo },
        });
      }

      // Check hostname match
      const hostname = new URL(httpsUrl).hostname;
      const certHostnames = this.extractCertHostnames(certInfo);
      evidence.hostnameMatch = certHostnames.includes(hostname) || certHostnames.some((h) => h === hostname);
      if (!evidence.hostnameMatch && certHostnames.length > 0) {
        status = status === 'PASSED' ? 'WARNING' : status;
        score = Math.max(0, score - 5);
        risks.push({
          type: 'CERT_HOSTNAME_MISMATCH',
          severity: 'MEDIUM',
          title: 'Certificate Hostname Mismatch',
          description: `Certificate is not issued for ${hostname}. Certificate covers: ${certHostnames.join(', ')}.`,
          evidence: { requested: hostname, certHostnames },
        });
      }

      // Check for auto-generated/self-signed
      if (certInfo.autoGenerated) {
        risks.push({
          type: 'SELF_SIGNED_CERT',
          severity: 'LOW',
          title: 'Self-Signed Certificate Detected',
          description: 'The certificate appears to be self-signed or auto-generated.',
          evidence: { issuer: certInfo.issuer },
        });
      }

      // Check issuer
      evidence.issuer = certInfo.issuer;
    } catch (err: any) {
      status = 'NOT_AVAILABLE';
      score = 0;
      result = 'HTTPS not available';
      details = err.message || 'Could not establish HTTPS connection.';
      evidence.error = err.message;

      risks.push({
        type: 'NO_HTTPS',
        severity: 'HIGH',
        title: 'HTTPS Not Available',
        description: `The website does not support HTTPS or the connection failed: ${err.message}`,
        evidence: { url: httpsUrl, error: err.message },
      });
    }

    return {
      check: {
        checkType: 'SSL',
        status,
        score,
        result,
        details,
        evidence,
        checkedAt: new Date().toISOString(),
      },
      risks,
    };
  }

  static async fetchCertificate(url: string): Promise<any> {
    return new Promise((resolve, reject) => {
      const parsed = new URL(url);
      const options = {
        hostname: parsed.hostname,
        port: parsed.port ? parseInt(parsed.port) : 443,
        path: parsed.pathname || '/',
        method: 'GET',
        rejectUnauthorized: false,
        requestCert: true,
      };

      const req = https.request(options, (res) => {
        const cert = res.socket as any;
        if (!cert || !cert.getCertificate) {
          reject(new Error('No certificate available'));
          return;
        }

        const certData = cert.getCertificate();
        const issuer = certData.issuer;
        const subject = certData.subject;
        const validFrom = new Date(certData.valid_before);
        const validTo = new Date(certData.valid_after);
        const now = new Date();

        const autoGenerated = this.isAutoGenerated(certData);

        resolve({
          subject,
          issuer: issuer?.O || issuer?.CN || issuer?.o || 'Unknown',
          validFrom: validFrom.toISOString(),
          validTo: validTo.toISOString(),
          valid: now >= validFrom && now <= validTo,
          autoGenerated,
          raw: {
            subject: certData.subject,
            issuer: certData.issuer,
          },
        });
        res.resume();
      });

      req.on('error', (err) => {
        reject(err);
      });

      req.setTimeout(10000, () => {
        req.destroy();
        reject(new Error('Certificate request timeout'));
      });

      req.end();
    });
  }

  static isAutoGenerated(certData: any): boolean {
    const issuer = certData.issuer;
    if (!issuer) return true;
    const issuerStr = JSON.stringify(issuer).toLowerCase();
    return (
      issuerStr.includes('letsencrypt') === false &&
      (issuerStr.includes('self-signed') ||
        issuerStr.includes('default') ||
        issuerStr.includes('test') ||
        issuer.CN === issuer.O)
    );
  }

  static extractCertHostnames(certData: any): string[] {
    const hostnames: string[] = [];
    try {
      const altName = certData.subjectAltName;
      if (altName) {
        altName.split(',').forEach((part: string) => {
          const trimmed = part.trim();
          if (trimmed.startsWith('DNS:')) {
            hostnames.push(trimmed.substring(4));
          }
        });
      }
    } catch {}
    if (hostnames.length === 0 && certData.subject?.CN) {
      hostnames.push(certData.subject.CN);
    }
    return hostnames;
  }
}